-- ATENÇÃO: material de referência. Revise o banco, o escopo e os filtros antes de executar comandos destrutivos.

SET HEADING OFF
SET PAGESIZE 0
SET LINESIZE 1000
SET VERIFY OFF
SET ECHO OFF

SPOOL /home/oracle/SINONIMOS.SQL
SELECT 'CREATE OR REPLACE PUBLIC SYNONYM ' || OBJECT_NAME || ' FOR ' || 'INFOSAUDE' || '.' || OBJECT_NAME || ';' FROM ALL_OBJECTS WHERE OWNER = 'INFOSAUDE'
AND OBJECT_TYPE IN (SELECT DISTINCT OBJECT_TYPE FROM ALL_OBJECTS);
SPOOL OFF

SPOOL /home/oracle/GRANT.SQL
SELECT 'GRANT SELECT, INSERT, UPDATE, DELETE ON ' || OBJECT_NAME || ' TO ' || 'ROLE_INFOSAUDE' || ';'
FROM ALL_OBJECTS WHERE OWNER = 'INFOSAUDE'
AND OBJECT_TYPE IN (SELECT DISTINCT OBJECT_TYPE FROM ALL_OBJECTS)
AND OBJECT_TYPE='TABLE';
SPOOL OFF

spool /home/oracle/OBJETOS.SQL
SELECT 'ALTER ' || CASE WHEN OBJECT_TYPE = 'PACKAGE BODY' THEN 'PACKAGE' ELSE OBJECT_TYPE END || ' ' || OBJECT_NAME || ' COMPILE;'
FROM USER_OBJECTS WHERE STATUS='INVALID'
AND OBJECT_TYPE IN ('VIEW', 'PROCEDURE', 'TRIGGER','PACKAGE','PACKAGE BODY','FUNCTION')
AND OBJECT_NAME NOT LIKE 'BIN$%';
SPOOL OFF

@/home/oracle/SINONIMOS.SQL
@/home/oracle/GRANT.SQL
@/home/oracle/OBJETOS.SQL

TRUNCATE TABLE INFOSAUDE.LOG_VERSAO DROP STORAGE;
