-- ATENÇÃO: material de referência. Revise o banco, o escopo e os filtros antes de executar comandos destrutivos.

ALTER PROFILE DEFAULT LIMIT PASSWORD_LIFE_TIME UNLIMITED;

CREATE USER INFOSAUDE
IDENTIFIED BY VALUES '74B82D7CAA2A90CD'
DEFAULT TABLESPACE INFOSAUDE_DATA
TEMPORARY TABLESPACE TEMP
QUOTA UNLIMITED ON INFOSAUDE_DATA
PROFILE DEFAULT ACCOUNT UNLOCK;

CREATE USER ANIMATI
IDENTIFIED BY VALUES '0634468578244872'
DEFAULT TABLESPACE INFOSAUDE_DATA
TEMPORARY TABLESPACE TEMP
QUOTA UNLIMITED ON INFOSAUDE_DATA
PROFILE DEFAULT ACCOUNT UNLOCK;

GRANT CREATE SESSION TO ANIMATI;

CREATE USER SYBSA
IDENTIFIED BY VALUES 'B2EA43C13215FEE2'
DEFAULT TABLESPACE INFOSAUDE_DATA
TEMPORARY TABLESPACE TEMP
QUOTA UNLIMITED ON INFOSAUDE_DATA
PROFILE DEFAULT ACCOUNT UNLOCK;

CREATE USER BACKUP
IDENTIFIED BY VALUES '44B2CA8B30522B76'
DEFAULT TABLESPACE INFOSAUDE_DATA
TEMPORARY TABLESPACE TEMP
QUOTA UNLIMITED ON INFOSAUDE_DATA
PROFILE DEFAULT ACCOUNT UNLOCK;

CREATE USER INTEGRACAO
IDENTIFIED BY VALUES 'C3398D0691E38788'
DEFAULT TABLESPACE INFOSAUDE_DATA
TEMPORARY TABLESPACE TEMP
QUOTA UNLIMITED ON INFOSAUDE_DATA
PROFILE DEFAULT ACCOUNT UNLOCK;

GRANT ADMINISTER DATABASE TRIGGER TO INFOSAUDE;

GRANT ADMINISTER DATABASE TRIGGER TO SYBSA;

GRANT CREATE SESSION TO INTEGRACAO;

CREATE ROLE ROLE_INFOSAUDE;

GRANT SELECT ON V_$SESSION TO ROLE_INFOSAUDE;

GRANT SELECT ON V_$SESSION TO INFOSAUDE;

CREATE ROLE ROLE_READONLY;

CREATE ROLE ROLE_INFODEVELOPER;

GRANT CREATE SESSION,EXECUTE ANY PROCEDURE, EXECUTE ANY TYPE TO ROLE_INFOSAUDE;

GRANT CREATE SESSION TO INFOSAUDE, SYBSA WITH ADMIN OPTION;

GRANT ALTER ANY DIMENSION,
      ALTER ANY INDEX,
      ALTER ANY INDEXTYPE,
      ALTER ANY LIBRARY,
      ALTER ANY OUTLINE,
      ALTER ANY PROCEDURE,
      ALTER ANY SEQUENCE,
      ALTER ANY SNAPSHOT,
      ALTER ANY TABLE,
      ALTER ANY TRIGGER,
      ALTER ANY TYPE,
      ALTER USER,
      COMMENT ANY TABLE,
      CREATE ANY CONTEXT,
      CREATE ANY DIMENSION,
      CREATE ANY INDEX,
      CREATE ANY INDEXTYPE,
      CREATE ANY LIBRARY,
      CREATE ANY OPERATOR,
      CREATE ANY OUTLINE,
      CREATE ANY PROCEDURE,
      CREATE ANY SEQUENCE,
      CREATE ANY SNAPSHOT,
      CREATE ANY SYNONYM,
      CREATE ANY TABLE,
      CREATE ANY TRIGGER,
      CREATE ANY TYPE,
      CREATE ANY VIEW,
      CREATE PUBLIC SYNONYM,
      CREATE SESSION,
      CREATE USER,
      DELETE ANY TABLE,
      DROP ANY CONTEXT,
      DROP ANY DIMENSION,
      DROP ANY INDEX,
      DROP ANY INDEXTYPE,
      DROP ANY LIBRARY,
      DROP ANY OPERATOR,
      DROP ANY OUTLINE,
      DROP ANY PROCEDURE,
      DROP ANY SEQUENCE,
      DROP ANY SNAPSHOT,
      DROP ANY SYNONYM,
      DROP ANY TABLE,
      DROP ANY TRIGGER,
      DROP ANY TYPE,
      DROP ANY VIEW,
      DROP PUBLIC SYNONYM,
      GRANT ANY OBJECT PRIVILEGE,
      INSERT ANY TABLE,
      SELECT ANY SEQUENCE,
      SELECT ANY TABLE,
      CREATE ROLE,
      UPDATE ANY TABLE
      TO ROLE_INFODEVELOPER;

GRANT ROLE_INFOSAUDE TO INFOSAUDE, SYBSA WITH ADMIN OPTION;

GRANT ROLE_INFODEVELOPER TO INFOSAUDE, SYBSA;

GRANT ALTER SYSTEM TO SYBSA;

GRANT ALTER SYSTEM TO INFOSAUDE;

CREATE ROLE ROLE_CRIARUSUARIOS;

GRANT DROP USER, ALTER USER, CREATE USER TO ROLE_CRIARUSUARIOS;

GRANT DROP USER, ALTER USER, CREATE USER TO INFOSAUDE, SYBSA;

GRANT SELECT ON SYS.DBA_USERS TO SYBSA;

GRANT SELECT ON SYS.DBA_USERS TO INFOSAUDE;

GRANT ROLE_CRIARUSUARIOS TO INFOSAUDE WITH ADMIN OPTION;

GRANT ROLE_INFODEVELOPER TO INFOSAUDE WITH ADMIN OPTION;

GRANT DEBUG CONNECT SESSION TO ROLE_INFODEVELOPER;

GRANT DEBUG ANY PROCEDURE TO ROLE_INFODEVELOPER;

GRANT DEBUG CONNECT SESSION TO INFOSAUDE;

GRANT DEBUG ANY PROCEDURE TO INFOSAUDE;

GRANT EXECUTE ON SYS.DBMS_CRYPTO TO INFOSAUDE;

GRANT SELECT ON SYS.V_$SESSION TO INFOSAUDE;

GRANT CREATE SESSION, IMP_FULL_DATABASE, EXP_FULL_DATABASE TO BACKUP;

GRANT SELECT ON DBA_DATAPUMP_JOBS TO INFOSAUDE, BACKUP;

CREATE USER CONSULTA
IDENTIFIED BY VALUES '4CF22F0901A7700D'
DEFAULT TABLESPACE INFOSAUDE_DATA
TEMPORARY TABLESPACE TEMP
QUOTA UNLIMITED ON INFOSAUDE_DATA
PROFILE DEFAULT ACCOUNT UNLOCK;

CREATE ROLE ROLE_CONSULTA;

GRANT CREATE SESSION TO CONSULTA;

GRANT SELECT ANY TABLE TO ROLE_CONSULTA;

GRANT ROLE_CONSULTA TO CONSULTA;

GRANT SELECT ON DBA_OBJECTS TO ROLE_INFOSAUDE;
